### ISSUE TITLE
Nil point dereference when search query returns 0 results

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#270]
The collector has a bug where if no repos are returned, a nil panic is given and crashes the collector. 

The search query was `org:liatrio archived:false topic:o11y`

```
2024-01-23 16:15:17 2024-01-23T21:15:17.028Z    info    service@v0.92.0/service.go:177  Everything is ready. Begin running and processing data.
2024-01-23 16:15:30 panic: runtime error: invalid memory address or nil pointer dereference
2024-01-23 16:15:30 [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1faafb0]
2024-01-23 16:15:30 
2024-01-23 16:15:30 goroutine 77 [running]:
2024-01-23 16:15:30 go.opentelemetry.io/collector/pdata/pmetric.NumberDataPoint.SetStartTimestamp(...)
2024-01-23 16:15:30     /home/runner/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.0.1/pmetric/generated_numberdatapoint.go:62
2024-01-23 16:15:30 github.com/liatrio/liatrio-otel-collector/receiver/gitproviderreceiver/internal/metadata.(*metricGitRepositoryBranchTime).recordDataPoint(0x4000154300?, 0x17ad1673004991a6, 0x17ad167554973cb2, 0xdcb, {0x4000983ae8, 0x14}, {0x4000587e00, 0xc})
2024-01-23 16:15:30     /home/runner/work/liatrio-otel-collector/liatrio-otel-collector/receiver/gitproviderreceiver/internal/metadata/generated_metrics.go:294 +0x170
2024-01-23 16:15:30 github.com/liatrio/liatrio-otel-collector/receiver/gitproviderreceiver/internal/metadata.(*MetricsBuilder).RecordGitRepositoryBranchTimeDataPoint(...)
2024-01-23 16:15:30     /home/runner/work/liatrio-otel-collector/liatrio-otel-collector/receiver/gitproviderreceiver/internal/metadata/generated_metrics.go:858
2024-01-23 16:15:30 github.com/liatrio/liatrio-otel-collector/receiver/gitproviderreceiver/internal/scraper/githubscraper.(*githubScraper).scrape.func1()
2024-01-23 16:15:30     /home/runner/work/liatrio-otel-collector/liatrio-otel-collector/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go:132 +0x5c4
2024-01-23 16:15:30 created by github.com/liatrio/liatrio-otel-collector/receiver/gitproviderreceiver/internal/scraper/githubscraper.(*githubScraper).scrape in goroutine 95
2024-01-23 16:15:30     /home/runner/work/liatrio-otel-collector/liatrio-otel-collector/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go:102 +0x7a8
```

**Comment by adrielp** [comment]
This has been resolved from some other commit and is no longer an issue.
